import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs/promises';import assert from 'node:assert/strict';
process.on('uncaughtException',e=>{console.error('TEST FAILED:',e.message,'code:',e.code,'position:',e.position,'detail:',e.detail);process.exit(1)});
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,phone_confirmed_at timestamptz,is_anonymous boolean default false);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;
grant usage on schema auth to anon,authenticated,service_role;grant execute on all functions in schema auth to anon,authenticated,service_role;
create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key,bucket_id text);alter table storage.objects enable row level security;`);
const sql=(await fs.readFile('supabase/setup.sql','utf8')).replace('create extension if not exists pgcrypto;','');
await db.exec(sql);
await db.exec(sql);
const conditionMigration=await fs.readFile('supabase/migrations/20261009210000_admin_condition_grades.sql','utf8');
await db.exec(conditionMigration);
const priceChangeMigration=await fs.readFile('supabase/migrations/20261009220000_listing_price_changes.sql','utf8');
await db.exec(priceChangeMigration);
const collateralImagesMigration=await fs.readFile('supabase/migrations/20261009230000_collateral_images.sql','utf8');
await db.exec(collateralImagesMigration);
const listingGalleriesMigration=await fs.readFile('supabase/migrations/20261009240000_listing_image_galleries.sql','utf8');
await db.exec(listingGalleriesMigration);
const level4ListingMigration=await fs.readFile('supabase/migrations/20261009250000_level4_direct_listing_publish.sql','utf8');
await db.exec(level4ListingMigration);
const dashboardMetricsMigration=await fs.readFile('supabase/migrations/20261009260000_real_dashboard_metrics.sql','utf8');
await db.exec(dashboardMetricsMigration);
const level4AuthorizationBypassMigration=await fs.readFile('supabase/migrations/20261009270000_level4_authorization_bypass.sql','utf8');
await db.exec(level4AuthorizationBypassMigration);
const listingManagementMigration=await fs.readFile('supabase/migrations/20261009280000_listing_management.sql','utf8');
await db.exec(listingManagementMigration);
const activeSettingsPolicyMigration=await fs.readFile('supabase/migrations/20261009290000_active_settings_policy.sql','utf8');
await db.exec(activeSettingsPolicyMigration);
console.log('PASS: SQL installer executes and safely reruns on PostgreSQL');
const maker='11111111-1111-4111-8111-111111111111',approver='22222222-2222-4222-8222-222222222222',buyer='33333333-3333-4333-8333-333333333333',other='44444444-4444-4444-8444-444444444444',noMfaStaff='55555555-5555-4555-8555-555555555555',secondLevel4='66666666-6666-4666-8666-666666666666';
await db.exec(`insert into auth.users(id,email,email_confirmed_at) values('${maker}','maker@test.invalid',now()),('${approver}','approver@test.invalid',now()),('${buyer}','buyer@test.invalid',now()),('${other}','other@test.invalid',now()),('${noMfaStaff}','no-mfa@test.invalid',now()),('${secondLevel4}','second-level4@test.invalid',now());
insert into public.staff_profiles(user_id,full_name,security_level,is_active,mfa_required) values('${maker}','Maker',2,true,false),('${approver}','Approver',3,true,true),('${noMfaStaff}','Admin without MFA',4,true,false),('${secondLevel4}','Second Level 4',4,true,false);
insert into public.loans_bridge(id,source_system,external_loan_id,outstanding_amount) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','test','LN-1',850000);
insert into public.collateral_assets(id,loan_bridge_id,asset_ref,title,category,created_by) values('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','COL-1','Test console','Gaming','${maker}');`);
async function as(role,id,aal='aal2'){await db.exec(`reset role;select set_config('request.jwt.claim.sub','${id||''}',false);select set_config('request.jwt.claims','${JSON.stringify({role,aal})}',false);set role ${role};`)}
async function rejects(sql,pattern){try{await db.query(sql);assert.fail('Expected rejection: '+sql)}catch(e){assert.match(e.message,pattern)}}
await as('anon');assert.equal((await db.query('select * from public.public_catalog')).rows.length,0);await rejects('select * from public.loans_bridge',/permission denied/);await rejects('select * from public.collateral_assets',/permission denied/);console.log('PASS: anonymous private data denied');
await as('authenticated',maker);const auth=(await db.query(`select public.request_authorization('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','{"basis":"recovery approved","reference_no":"AUTH-1","reason":"Legal approval recorded","evidence_path":"evidence/test.pdf"}') as d`)).rows[0].d;
await rejects(`select public.approve_action('${auth.id}','approved','Own approval')`,/permission|MFA/);console.log('PASS: Level 2 cannot call approval API');
await db.exec('reset role');await db.exec(`update public.staff_profiles set security_level=3 where user_id='${maker}'`);await as('authenticated',maker);await rejects(`select public.approve_action('${auth.id}','approved','Own approval')`,/Independent/);console.log('PASS: maker cannot approve own request');
await as('authenticated',approver,'aal1');await rejects(`select public.approve_action('${auth.id}','approved','Review complete')`,/permission|MFA/);console.log('PASS: senior staff MFA required');
await as('authenticated',noMfaStaff,'aal1');assert.equal((await db.query('select private.staff_level() as level')).rows[0].level,4);console.log('PASS: staff profile can explicitly waive MFA');
await as('authenticated',approver);await db.query(`select public.approve_action('${auth.id}','approved','Review complete')`);
await db.exec('reset role');const authorization=(await db.query('select id from public.sale_authorizations')).rows[0].id;await db.exec(`update public.staff_profiles set security_level=2 where user_id='${maker}'`);
await rejects(`select public.create_listing('${JSON.stringify({asset_id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',slug:'l2-no-authorization',method:'fixed_price',title:'Level 2 without authorization',description:'Must be rejected.',price:'1000',collection_point:'Blantyre',terms_version:'test-v1',image:'https://example.invalid/no-auth.webp',reason:'Missing authorization'})}') as d`,/Approved sale authorization required/);
await as('authenticated',maker);const listing=(await db.query(`select public.create_listing('${JSON.stringify({asset_id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',sale_authorization_id:authorization,slug:'test-console',method:'auction',title:'Test Console',description:'Public description',price:'100000',increment:'10000',duration_hours:'2',collection_point:'Blantyre',terms_version:'test-v1',image:'https://example.invalid/test.webp',defects:'Used',reason:'Publish approved asset'})}') as d`)).rows[0].d;
await as('anon');assert.equal((await db.query('select * from public.public_catalog')).rows.length,0);console.log('PASS: pending listings hidden');
await db.exec('reset role');const req=(await db.query(`select id from public.approval_requests where action_type='publish_listing'`)).rows[0].id;
await as('authenticated',approver);await db.query(`select public.approve_action('${req}','approved','Publication review complete')`);
await as('anon');const cat=(await db.query('select * from public.public_catalog')).rows[0];assert.equal(cat.title,'Test Console');assert.equal(cat.category,'Gaming');assert.equal(cat.external_loan_id,undefined);assert.equal(cat.borrower_reference,undefined);console.log('PASS: public catalogue preserves selected category and safe projection');
await as('authenticated',buyer);await rejects(`insert into public.bids(auction_listing_id,bidder_id,amount) values('${listing.id}','${buyer}',100000)`,/permission denied/);
await db.query(`select public.place_bid('${listing.id}',100000)`);await rejects(`select public.place_bid('${listing.id}',110000)`,/highest bidder/);await as('authenticated',other);await rejects(`select public.place_bid('${listing.id}',105000)`,/below/);await db.query(`select public.place_bid('${listing.id}',110000)`);console.log('PASS: bids use authoritative minimum and reject direct writes');
await as('authenticated',maker);await rejects(`select public.request_change('listing_price_change','${listing.id}','{"price":125000,"reason":"Raise starting bid"}')`,/Starting bid is locked/);console.log('PASS: auction starting bid cannot change after bidding begins');
await db.exec('reset role');await db.exec(`update public.auctions set ends_at=clock_timestamp()+interval '30 seconds' where listing_id='${listing.id}'`);await as('authenticated',buyer);await db.query(`select public.place_bid('${listing.id}',120000)`);await db.exec('reset role');assert.equal((await db.query(`select extension_count from public.auctions where listing_id='${listing.id}'`)).rows[0].extension_count,1);console.log('PASS: late qualifying bid extends auction');
await db.exec(`update public.auctions set starts_at=clock_timestamp()-interval '1 hour',ends_at=clock_timestamp()-interval '1 second' where listing_id='${listing.id}'`);await as('authenticated',other);await rejects(`select public.place_bid('${listing.id}',130000)`,/not open/);await as('service_role');await db.query('select public.close_auctions()');await db.query('select public.close_auctions()');await db.exec('reset role');const orders=(await db.query('select * from public.orders')).rows;assert.equal(orders.length,1);const order=orders[0];assert.equal(order.buyer_id,buyer);console.log('PASS: server closure rejects late bid and creates only one winner order');
await as('authenticated',other);assert.equal((await db.query('select * from public.orders')).rows.length,0);await rejects(`update public.orders set status='paid' where id='${order.id}'`,/permission denied/);console.log('PASS: buyer cannot read another buyer order or mark paid');
await as('authenticated',buyer);const payment=(await db.query(`select public.begin_payment('${order.id}') as d`)).rows[0].d;await rejects(`select public.confirm_verified_payment('${payment.tx_ref}',120000,'MWK','provider-1','{}')`,/permission denied/);
await as('service_role');await rejects(`select public.confirm_verified_payment('${payment.tx_ref}',120001,'MWK','provider-1','{}')`,/mismatch/);await db.query(`select public.confirm_verified_payment('${payment.tx_ref}',120000,'MWK','provider-1','{}')`);await db.query(`select public.confirm_verified_payment('${payment.tx_ref}',120000,'MWK','provider-1','{}')`);await db.exec('reset role');assert.equal((await db.query('select * from public.settlements')).rows.length,1);assert.equal((await db.query("select sum(direction*amount) as total from public.settlement_lines where line_type<>'SHORTFALL'")).rows[0].total,'0.00');console.log('PASS: exact payment match, idempotency and balanced settlement');
await rejects('delete from public.audit_events',/Append-only/);await rejects('delete from public.bids',/Append-only/);console.log('PASS: immutable bids and audit');
await as('authenticated',maker);await rejects(`select public.release_asset('${order.id}','invalid','Buyer','ID-1','Handover')`,/must match/);console.log('PASS: release blocked without approval and valid token');

await db.exec('reset role');
const settlementId=(await db.query('select id from public.settlements')).rows[0].id;
await as('authenticated',maker);
const settleRequest=(await db.query(`select public.request_change('settlement','${settlementId}','{"reason":"Finance review"}') as d`)).rows[0].d;
await as('authenticated',approver);await db.query(`select public.approve_action('${settleRequest.id}','approved','Finance allocations checked')`);
await db.exec('reset role');assert.equal((await db.query('select * from public.integration_outbox')).rows.length,1);console.log('PASS: settlement approval creates durable loan outbox');
await as('authenticated',noMfaStaff,'aal1');
const settingsRequest=(await db.query(`select public.request_change('settings_change',gen_random_uuid(),'${JSON.stringify({high_value_threshold:100000,extension_window:180,extension_seconds:90,max_extensions:12})}') as d`)).rows[0].d;
await as('authenticated',secondLevel4,'aal1');await db.query(`select public.approve_action('${settingsRequest.id}','approved','Updated policy reviewed')`);
const activeSettings=(await db.query('select settings from public.system_settings order by created_at desc limit 1')).rows[0].settings;
assert.equal(Number(activeSettings.high_value_threshold),100000);assert.equal(Number(activeSettings.extension_window),180);
await as('authenticated',maker);
const releaseRequest=(await db.query(`select public.request_change('release','${order.id}','{"collector_name":"Buyer","collector_ref":"ID-***-1","reason":"Identity checked"}') as d`)).rows[0].d;
assert.equal((await db.query(`select required_min_level from public.approval_requests where id='${releaseRequest.id}'`)).rows[0].required_min_level,4);
await as('authenticated',approver);await rejects(`select public.approve_action('${releaseRequest.id}','approved','Collector authorized')`,/Independent eligible approver/);
await as('authenticated',noMfaStaff,'aal1');await db.query(`select public.approve_action('${releaseRequest.id}','approved','High-value collector authorized')`);
await as('authenticated',buyer);const note=(await db.query("select message from public.notifications where kind='collection_ready'")).rows[0].message;const releaseCode=note.split(': ')[1];
await as('authenticated',maker);await db.query(`select public.release_asset('${order.id}','${releaseCode}','Buyer','ID-***-1','Handover signed')`);await rejects(`select public.release_asset('${order.id}','${releaseCode}','Buyer','ID-***-1','Duplicate handover')`,/must match/);console.log('PASS: high-value release requires Level 4 approval and approved identity-matched release is single use');
await as('authenticated',approver);const metrics=(await db.query('select public.dashboard_metrics() as d')).rows[0].d;assert.equal(metrics.chart.length,6);assert.equal(metrics.kpis.recovered,120000);assert.equal(metrics.chart.at(-1).gross,120000);assert.equal(metrics.chart.at(-1).recovered,120000);const pendingApprovals=(await db.query("select count(*)::integer as count from public.approval_requests where status='pending'")).rows[0].count;const awaitingCollection=(await db.query("select count(*)::integer as count from public.orders where status='paid'")).rows[0].count;const pendingLoanPosts=(await db.query("select count(*)::integer as count from public.integration_outbox where status='pending'")).rows[0].count;assert.equal(metrics.attention.pending_approvals,pendingApprovals);assert.equal(metrics.attention.awaiting_collection,awaitingCollection);assert.equal(metrics.attention.loan_pending,pendingLoanPosts);console.log('PASS: dashboard metrics and attention counts use the approved ledger and live workflow tables');
await as('authenticated',maker);await rejects(`select public.create_asset('{"external_loan_id":"LN-MISSING","asset_ref":"COL-MISSING","title":"Missing loan","category":"Other","valuation_amount":1000,"custody_location":"Blantyre","condition_notes":"Good","reason":"New item"}')`,/Loan not synchronized/);
const standalone=(await db.query(`select public.create_asset('{"asset_ref":"COL-STANDALONE-1","title":"Standalone console","category":"Gaming","valuation_amount":200000,"custody_location":"Blantyre office","condition_notes":"Tested and in good condition","reason":"Standalone inventory"}') as d`)).rows[0].d;assert.equal(standalone.loan_bridge_id,null);assert.equal(standalone.currency,'MWK');
const standaloneAuth=(await db.query(`select public.request_authorization('${standalone.id}','{"basis":"Institution-owned inventory","reference_no":"AUTH-STANDALONE-1","reason":"Ownership evidence reviewed","evidence_path":"evidence/standalone-1.pdf"}') as d`)).rows[0].d;
await as('authenticated',approver);await db.query(`select public.approve_action('${standaloneAuth.id}','approved','Ownership evidence verified')`);
const standaloneAuthorization=(await db.query(`select id from public.sale_authorizations where asset_id='${standalone.id}'`)).rows[0].id;
await as('authenticated',maker);const standaloneListing=(await db.query(`select public.create_listing('${JSON.stringify({asset_id:standalone.id,sale_authorization_id:standaloneAuthorization,slug:'standalone-console',method:'fixed_price',title:'Standalone console',description:'Institution-owned item available for sale.',price:'200000',increment:'10000',duration_hours:'72',collection_point:'Blantyre office',terms_version:'test-v1',image:'https://example.invalid/standalone.webp',images:['https://example.invalid/standalone.webp','https://example.invalid/standalone-detail.webp'],defects:'No known defects',reason:'Publish standalone inventory'})}') as d`)).rows[0].d;
const publishRequest=(await db.query(`select id from public.approval_requests where action_type='publish_listing' and entity_id='${standaloneListing.id}'`)).rows[0].id;await as('authenticated',approver);await db.query(`select public.approve_action('${publishRequest}','approved','Standalone sale details verified')`);
await as('anon');const standaloneCatalog=(await db.query(`select id,images,image from public.public_catalog where id='${standaloneListing.id}'`)).rows[0];assert.equal(standaloneCatalog.images.length,2);assert.equal(standaloneCatalog.image,standaloneCatalog.images[0]);
await as('authenticated',maker);const priceRequest=(await db.query(`select public.request_change('listing_price_change','${standaloneListing.id}','{"price":210000,"reason":"Updated market valuation"}') as d`)).rows[0].d;
assert.equal(priceRequest.proposed_values.old_price,200000);
await rejects(`select public.approve_action('${priceRequest.id}','approved','Maker cannot self-approve')`,/Independent|permission|MFA/);
await as('anon');assert.equal((await db.query(`select price from public.public_catalog where id='${standaloneListing.id}'`)).rows[0].price,'200000.00');
await as('authenticated',approver);await db.query(`select public.approve_action('${priceRequest.id}','approved','Independent price review complete')`);
await as('anon');assert.equal((await db.query(`select price from public.public_catalog where id='${standaloneListing.id}'`)).rows[0].price,'210000.00');
await as('authenticated',buyer);const standaloneOrder=(await db.query(`select public.buy_now('${standaloneListing.id}') as d`)).rows[0].d;const standalonePayment=(await db.query(`select public.begin_payment('${standaloneOrder.id}') as d`)).rows[0].d;
await as('service_role');const standalonePaid=(await db.query(`select public.confirm_verified_payment('${standalonePayment.tx_ref}',210000,'MWK','provider-standalone','{}') as d`)).rows[0].d;
await db.exec('reset role');const standaloneSettlement=(await db.query(`select * from public.settlements where id='${standalonePaid.settlement_id}'`)).rows[0];assert.equal(standaloneSettlement.loan_sync,'not_applicable');assert.equal((await db.query(`select amount from public.settlement_lines where settlement_id='${standalonePaid.settlement_id}' and line_type='RECOVERY_TO_LOAN'`)).rows[0].amount,'0.00');assert.equal((await db.query(`select amount from public.settlement_lines where settlement_id='${standalonePaid.settlement_id}' and line_type='OWNER_SURPLUS'`)).rows[0].amount,'210000.00');console.log('PASS: standalone asset authorization, publication, approved repricing and payment settlement');
await as('authenticated',maker);const cashAsset=(await db.query(`select public.create_asset('{"asset_ref":"COL-CASH-1","title":"Cash sale laptop","category":"Electronics","valuation_amount":300000,"custody_location":"Blantyre office","condition_notes":"Inspected","reason":"Cash counter inventory"}') as d`)).rows[0].d;
const cashAuth=(await db.query(`select public.request_authorization('${cashAsset.id}','{"basis":"Institution-owned item","reference_no":"AUTH-CASH-1","reason":"Ownership checked","evidence_path":"evidence/cash-1.pdf"}') as d`)).rows[0].d;
await as('authenticated',approver);await db.query(`select public.approve_action('${cashAuth.id}','approved','Ownership checked')`);
const cashAuthorization=(await db.query(`select id from public.sale_authorizations where asset_id='${cashAsset.id}'`)).rows[0].id;
await as('authenticated',maker);const cashListing=(await db.query(`select public.create_listing('${JSON.stringify({asset_id:cashAsset.id,sale_authorization_id:cashAuthorization,slug:'cash-sale-laptop',method:'fixed_price',title:'Cash sale laptop',description:'Approved laptop for sale.',price:'300000',increment:'10000',duration_hours:'72',collection_point:'Blantyre office',terms_version:'test-v1',image:'https://example.invalid/cash.webp',defects:'Used',reason:'List cash-sale item'})}') as d`)).rows[0].d;
const cashPublish=(await db.query(`select id from public.approval_requests where action_type='publish_listing' and entity_id='${cashListing.id}'`)).rows[0].id;await as('authenticated',approver);await db.query(`select public.approve_action('${cashPublish}','approved','Listing details checked')`);
const cashResult=(await db.query(`select public.record_cash_sale('${cashListing.id}','TILL-2026-001','Walk-in buyer','0999000000','Cash received at office') as d`)).rows[0].d;assert.equal(cashResult.status,'paid');
const cashOrder=(await db.query(`select * from public.orders where id='${cashResult.order_id}'`)).rows[0];assert.equal(cashOrder.status,'paid');assert.equal(cashOrder.payment_method,'cash');assert.equal(cashOrder.buyer_id,null);assert.equal(cashOrder.buyer_name,'Walk-in buyer');
assert.equal((await db.query(`select status from public.listings where id='${cashListing.id}'`)).rows[0].status,'sold');assert.equal((await db.query(`select provider from public.payments where order_id='${cashOrder.id}'`)).rows[0].provider,'cash');
const cashLines=(await db.query(`select sum(direction*amount) as total from public.settlement_lines where settlement_id='${cashResult.settlement_id}' and line_type<>'SHORTFALL'`)).rows[0];assert.equal(cashLines.total,'0.00');
await rejects(`select public.record_cash_sale('${cashListing.id}','TILL-2026-001','Duplicate buyer','','Duplicate receipt attempt')`,/only for live fixed-price/);
const cashLog=(await db.query(`select actor,action from public.admin_audit_log() where entity_id='${cashOrder.id}'`)).rows[0];assert.equal(cashLog.actor,'Approver');assert.equal(cashLog.action,'cash_sale.recorded');console.log('PASS: cash sale marks item sold, balances settlement, blocks repeat sale and logs staff actor');
await as('authenticated',maker);const cashRelease=(await db.query(`select public.request_change('release','${cashOrder.id}','{"collector_name":"Walk-in buyer","collector_ref":"ID-***-2","reason":"Cash order buyer identity recorded"}') as d`)).rows[0].d;
await as('authenticated',noMfaStaff,'aal1');const cashReleaseApproved=(await db.query(`select public.approve_action('${cashRelease.id}','approved','Cash sale collection approved') as d`)).rows[0].d;assert.ok(cashReleaseApproved.release_code);
await as('authenticated',maker);await db.query(`select public.release_asset('${cashOrder.id}','${cashReleaseApproved.release_code}','Walk-in buyer','ID-***-2','Signed handover')`);console.log('PASS: cash sale uses independent collection approval and single-use release');
await as('authenticated',maker);
const gradedAsset=(await db.query(`select public.create_asset('${JSON.stringify({title:'Condition grade test asset',category:'Other',valuation_amount:'1000',currency:'USD',custody_location:'Blantyre office',condition_grade:'New',image_paths:['assets/test-collateral.webp','assets/test-collateral-detail.webp'],reason:'Condition grade test'})}') as d`)).rows[0].d;
assert.match(gradedAsset.asset_ref,/^COL-\d{4}-[A-F0-9]{12}$/);
assert.equal(gradedAsset.condition_grade,'New');
assert.equal(gradedAsset.currency,'USD');
assert.deepEqual((await db.query(`select storage_path from public.asset_media where asset_id='${gradedAsset.id}' and media_type='public_image' order by sort_order`)).rows.map((row)=>row.storage_path),['assets/test-collateral.webp','assets/test-collateral-detail.webp']);
const gradeAuthorization=(await db.query(`select public.request_authorization('${gradedAsset.id}','{"basis":"Condition grade test","reference_no":"AUTH-GRADE-1","reason":"Test authorization","evidence_path":"evidence/grade-test.pdf"}') as d`)).rows[0].d;
await as('authenticated',approver);await db.query(`select public.approve_action('${gradeAuthorization.id}','approved','Condition grade test approved')`);
const gradeAuthorizationId=(await db.query(`select id from public.sale_authorizations where asset_id='${gradedAsset.id}'`)).rows[0].id;
await as('authenticated',maker);
const gradedListing=(await db.query(`select public.create_listing('${JSON.stringify({asset_id:gradedAsset.id,sale_authorization_id:gradeAuthorizationId,slug:'condition-grade-test',method:'fixed_price',title:'Condition grade test',description:'Test public description',price:'1000',collection_point:'Blantyre office',terms_version:'test-v1',image:'https://example.invalid/grade.webp',condition_grade:'Fair',defects:'None',reason:'Condition grade test'})}') as d`)).rows[0].d;
assert.equal(gradedListing.condition_grade,'Fair');
console.log('PASS: asset and listing condition grades persist through their admin RPCs');

const level4Asset=(await db.query(`select public.create_asset('${JSON.stringify({title:'Level 4 direct listing asset',category:'Other',valuation_amount:'5000',currency:'MWK',custody_location:'Blantyre office',image_paths:['assets/level4-direct.webp'],reason:'Level 4 listing test'})}') as d`)).rows[0].d;
const level4Authorization=(await db.query(`select public.request_authorization('${level4Asset.id}','{"basis":"Level 4 listing test","reference_no":"AUTH-L4-DIRECT","reason":"Test authorization","evidence_path":"evidence/l4-direct.pdf"}') as d`)).rows[0].d;
await as('authenticated',approver);await db.query(`select public.approve_action('${level4Authorization.id}','approved','Sale authorization approved')`);
const level4AuthorizationId=(await db.query(`select id from public.sale_authorizations where asset_id='${level4Asset.id}'`)).rows[0].id;
await as('authenticated',noMfaStaff,'aal1');
const level4Listing=(await db.query(`select public.create_listing('${JSON.stringify({asset_id:level4Asset.id,sale_authorization_id:level4AuthorizationId,slug:'level4-direct-listing',method:'fixed_price',title:'Level 4 direct listing',description:'Published without a second listing approval.',price:'5000',collection_point:'Blantyre office',terms_version:'test-v1',images:['https://example.invalid/l4-front.webp','https://example.invalid/l4-side.webp'],reason:'Level 4 direct publication'})}') as d`)).rows[0].d;
assert.equal(level4Listing.status,'live');assert.equal(level4Listing.approved_by,noMfaStaff);
assert.equal(level4Listing.sale_authorization_id,level4AuthorizationId);
await as('anon');const level4PublicListing=(await db.query(`select * from public.public_catalog where id='${level4Listing.id}'`)).rows[0];assert.equal(level4PublicListing.title,'Level 4 direct listing');assert.equal(level4PublicListing.images.length,2);
await db.exec('reset role');assert.equal((await db.query(`select count(*)::integer as count from public.approval_requests where entity_id='${level4Listing.id}' and action_type='publish_listing'`)).rows[0].count,0);
console.log('PASS: Level 4 listings publish immediately with no listing approval request');

await as('authenticated',noMfaStaff,'aal1');
const level4BypassAsset=(await db.query(`select public.create_asset('${JSON.stringify({title:'Level 4 no authorization asset',category:'Other',valuation_amount:'4000',currency:'MWK',custody_location:'Blantyre office',image_paths:['assets/level4-no-auth.webp'],reason:'Level 4 authorization bypass test'})}') as d`)).rows[0].d;
const level4BypassListing=(await db.query(`select public.create_listing('${JSON.stringify({asset_id:level4BypassAsset.id,slug:'level4-no-authorization',method:'fixed_price',title:'Level 4 no authorization',description:'Published without sale authorization.',price:'4000',collection_point:'Blantyre office',terms_version:'test-v1',image:'https://example.invalid/l4-no-auth.webp',reason:'Level 4 direct publication without authorization'})}') as d`)).rows[0].d;
assert.equal(level4BypassListing.status,'live');assert.equal(level4BypassListing.sale_authorization_id,null);
const editedLevel4Listing=(await db.query(`select public.update_listing('${level4BypassListing.id}','${JSON.stringify({title:'Updated Lenovo PC',slug:'updated-lenovo-pc',description:'Updated public description.',price:'4500',collection_point:'Lilongwe office',condition_grade:'Excellent',defects:'Minor scratch on the lid',image:'https://example.invalid/l4-updated.webp',images:['https://example.invalid/l4-updated.webp','https://example.invalid/l4-detail.webp'],reason:'Corrected listing details and replaced photos'})}') as d`)).rows[0].d;
assert.equal(editedLevel4Listing.public_title,'Updated Lenovo PC');assert.equal(editedLevel4Listing.slug,'updated-lenovo-pc');
await as('authenticated',maker);await rejects(`select public.update_listing('${level4BypassListing.id}','{"title":"Unauthorized edit","slug":"unauthorized-edit","price":"4500"}')`,/permission/i);await rejects(`select public.archive_listings(array['${level4BypassListing.id}'::uuid])`,/permission/i);
await as('authenticated',noMfaStaff,'aal1');
await as('anon');const updatedPublicListing=(await db.query(`select * from public.public_catalog where id='${level4BypassListing.id}'`)).rows[0];assert.equal(updatedPublicListing.slug,'updated-lenovo-pc');assert.equal(updatedPublicListing.location,'Lilongwe office');assert.equal(updatedPublicListing.images[0],'https://example.invalid/l4-updated.webp');
await db.exec('reset role');console.log('PASS: Level 4 can publish without authorization and edit listing details and photos');

await as('authenticated',noMfaStaff,'aal1');
const archiveAssets=await Promise.all(['archive-selected-two','archive-preserve-one'].map(async (title,index)=>(await db.query(`select public.create_asset('${JSON.stringify({title,category:'Other',valuation_amount:'3000',currency:'MWK',custody_location:'Blantyre office',image_paths:[`assets/${title}.webp`],reason:'Listing archive test'})}') as d`)).rows[0].d));
const archiveListings=await Promise.all(archiveAssets.map(async (asset,index)=>(await db.query(`select public.create_listing('${JSON.stringify({asset_id:asset.id,slug:`archive-test-${index+1}`,method:'fixed_price',title:`Archive test ${index+1}`,description:'Archive workflow test listing.',price:'3000',collection_point:'Blantyre office',terms_version:'test-v1',image:`https://example.invalid/archive-${index+1}.webp`,reason:'Listing archive test'})}') as d`)).rows[0].d));
const archivedResult=(await db.query(`select public.archive_listings(array['${level4BypassListing.id}'::uuid,'${archiveListings[0].id}'::uuid]) as d`)).rows[0].d;
assert.equal(archivedResult.archived_count,2);
assert.equal((await db.query(`select count(*)::integer as count from public.listings where id in ('${level4BypassListing.id}','${archiveListings[0].id}') and status='archived'`)).rows[0].count,2);
await as('anon');assert.equal((await db.query(`select count(*)::integer as count from public.public_catalog where id in ('${level4BypassListing.id}','${archiveListings[0].id}')`)).rows[0].count,0);assert.equal((await db.query(`select count(*)::integer as count from public.public_catalog where id='${archiveListings[1].id}'`)).rows[0].count,1);
await db.exec('reset role');await as('authenticated',noMfaStaff,'aal1');
await rejects(`select public.archive_listings(array['${listing.id}'::uuid])`,/orders|bid history|sold or reserved/i);
await db.exec('reset role');console.log('PASS: multi-select archive removes only selected listings and preserves listings with transaction history');

await db.query(`insert into public.approval_requests(action_type,entity_type,entity_id,requested_by,required_min_level,reason) values('publish_listing','listing','${level4Listing.id}','${noMfaStaff}',3,'Existing Level 4 pending listing')`);
await db.query(`update public.listings set status='pending_approval',approved_by=null,publish_at=null where id='${level4Listing.id}'`);
await db.exec(`select set_config('request.jwt.claim.sub','',false);select set_config('request.jwt.claims','{}',false);`);
await db.exec(level4ListingMigration);
await db.exec(level4AuthorizationBypassMigration);
await db.exec(listingManagementMigration);
assert.equal((await db.query(`select status from public.listings where id='${level4Listing.id}'`)).rows[0].status,'live');
assert.equal((await db.query(`select status from public.approval_requests where entity_id='${level4Listing.id}' and action_type='publish_listing'`)).rows[0].status,'cancelled');
assert.equal((await db.query(`select id from public.public_catalog where id='${level4Listing.id}'`)).rows.length,1);
console.log('PASS: migration publishes existing eligible Level 4 listings and cancels their obsolete requests');

await as('authenticated',maker);
const level3Asset=(await db.query(`select public.create_asset('${JSON.stringify({title:'Level 3 reviewed listing asset',category:'Other',valuation_amount:'6000',currency:'MWK',custody_location:'Blantyre office',image_paths:['assets/level3-reviewed.webp'],reason:'Level 3 listing test'})}') as d`)).rows[0].d;
const level3Authorization=(await db.query(`select public.request_authorization('${level3Asset.id}','{"basis":"Level 3 listing test","reference_no":"AUTH-L3-REVIEW","reason":"Test authorization","evidence_path":"evidence/l3-review.pdf"}') as d`)).rows[0].d;
await as('authenticated',approver);await db.query(`select public.approve_action('${level3Authorization.id}','approved','Sale authorization approved')`);
const level3AuthorizationId=(await db.query(`select id from public.sale_authorizations where asset_id='${level3Asset.id}'`)).rows[0].id;
const level3Listing=(await db.query(`select public.create_listing('${JSON.stringify({asset_id:level3Asset.id,sale_authorization_id:level3AuthorizationId,slug:'level3-reviewed-listing',method:'fixed_price',title:'Level 3 reviewed listing',description:'Awaiting independent publication approval.',price:'6000',collection_point:'Blantyre office',terms_version:'test-v1',image:'https://example.invalid/l3-front.webp',reason:'Level 3 listing review'})}') as d`)).rows[0].d;
assert.equal(level3Listing.status,'pending_approval');
await as('anon');assert.equal((await db.query(`select * from public.public_catalog where id='${level3Listing.id}'`)).rows.length,0);
await db.exec('reset role');const level3Request=(await db.query(`select * from public.approval_requests where entity_id='${level3Listing.id}' and action_type='publish_listing'`)).rows[0];assert.equal(level3Request.requested_by,approver);assert.equal(level3Request.required_min_level,3);
console.log('PASS: Level 3 listings remain hidden pending independent Level 3 approval');
await as('authenticated',approver);
const currentMetrics=(await db.query('select public.dashboard_metrics() as d')).rows[0].d;
const currentMonthTotals=(await db.query(`select (select coalesce(sum(amount_due),0)::float8 from public.orders where date_trunc('month',created_at)=date_trunc('month',now()) and status in ('paid','released','closed','disputed')) as gross,(select coalesce(sum(sl.amount),0)::float8 from public.settlement_lines sl join public.settlements st on st.id=sl.settlement_id where date_trunc('month',st.created_at)=date_trunc('month',now()) and st.status in ('approved','posted_to_loan','closed') and sl.line_type='RECOVERY_TO_LOAN') as recovered,(select coalesce(sum(sl.amount),0)::float8 from public.settlement_lines sl join public.settlements st on st.id=sl.settlement_id where date_trunc('month',st.created_at)=date_trunc('month',now()) and st.status in ('approved','posted_to_loan','closed') and sl.line_type='OWNER_SURPLUS') as surplus`)).rows[0];
assert.deepEqual(currentMetrics.chart.at(-1),{month:currentMetrics.chart.at(-1).month,gross:currentMonthTotals.gross,recovered:currentMonthTotals.recovered,surplus:currentMonthTotals.surplus});
const attentionExpectations={
	pending_approvals:(await db.query("select count(*)::integer as count from public.approval_requests where status='pending'")).rows[0].count,
	awaiting_collection:(await db.query("select count(*)::integer as count from public.orders where status='paid'")).rows[0].count,
	loan_pending:(await db.query("select count(*)::integer as count from public.integration_outbox where status='pending'")).rows[0].count,
	loan_dead_letter:(await db.query("select count(*)::integer as count from public.integration_outbox where status='dead_letter'")).rows[0].count,
	loan_posted:(await db.query("select count(*)::integer as count from public.integration_outbox where status='posted'")).rows[0].count,
};
assert.deepEqual(currentMetrics.attention,attentionExpectations);
console.log('PASS: dashboard chart and attention panel report exact ledger/workflow data');
await db.close();console.log('All database security and workflow tests passed.');
