import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs/promises';import assert from 'node:assert/strict';
process.on('uncaughtException',e=>{console.error('TEST FAILED:',e.message,'code:',e.code,'position:',e.position,'detail:',e.detail);process.exit(1)});
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,phone_confirmed_at timestamptz,is_anonymous boolean default false);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;
grant usage on schema auth to anon,authenticated,service_role;grant execute on all functions in schema auth to anon,authenticated,service_role;
create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key,bucket_id text);alter table storage.objects enable row level security;`);
const sql=(await fs.readFile('supabase/setup.sql','utf8')).replace('create extension if not exists pgcrypto;','');
await db.exec(sql);
await db.exec(sql);
console.log('PASS: SQL installer executes and safely reruns on PostgreSQL');
const maker='11111111-1111-4111-8111-111111111111',approver='22222222-2222-4222-8222-222222222222',buyer='33333333-3333-4333-8333-333333333333',other='44444444-4444-4444-8444-444444444444';
await db.exec(`insert into auth.users(id,email,email_confirmed_at) values('${maker}','maker@test.invalid',now()),('${approver}','approver@test.invalid',now()),('${buyer}','buyer@test.invalid',now()),('${other}','other@test.invalid',now());
insert into public.staff_profiles(user_id,full_name,security_level,is_active) values('${maker}','Maker',2,true),('${approver}','Approver',3,true);
insert into public.loans_bridge(id,source_system,external_loan_id,outstanding_amount) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','test','LN-1',850000);
insert into public.collateral_assets(id,loan_bridge_id,asset_ref,title,category,created_by) values('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','COL-1','Test console','Gaming','${maker}');`);
async function as(role,id,aal='aal2'){await db.exec(`reset role;select set_config('request.jwt.claim.sub','${id||''}',false);select set_config('request.jwt.claims','${JSON.stringify({role,aal})}',false);set role ${role};`)}
async function rejects(sql,pattern){try{await db.query(sql);assert.fail('Expected rejection: '+sql)}catch(e){assert.match(e.message,pattern)}}
await as('anon');assert.equal((await db.query('select * from public.public_catalog')).rows.length,0);await rejects('select * from public.loans_bridge',/permission denied/);await rejects('select * from public.collateral_assets',/permission denied/);console.log('PASS: anonymous private data denied');
await as('authenticated',maker);const auth=(await db.query(`select public.request_authorization('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','{"basis":"recovery approved","reference_no":"AUTH-1","reason":"Legal approval recorded","evidence_path":"evidence/test.pdf"}') as d`)).rows[0].d;
await rejects(`select public.approve_action('${auth.id}','approved','Own approval')`,/permission|MFA/);console.log('PASS: Level 2 cannot call approval API');
await db.exec('reset role');await db.exec(`update public.staff_profiles set security_level=3 where user_id='${maker}'`);await as('authenticated',maker);await rejects(`select public.approve_action('${auth.id}','approved','Own approval')`,/Independent/);console.log('PASS: maker cannot approve own request');
await as('authenticated',approver,'aal1');await rejects(`select public.approve_action('${auth.id}','approved','Review complete')`,/permission|MFA/);console.log('PASS: senior staff MFA required');
await as('authenticated',approver);await db.query(`select public.approve_action('${auth.id}','approved','Review complete')`);
await db.exec('reset role');const authorization=(await db.query('select id from public.sale_authorizations')).rows[0].id;await db.exec(`update public.staff_profiles set security_level=2 where user_id='${maker}'`);
await as('authenticated',maker);const listing=(await db.query(`select public.create_listing('${JSON.stringify({asset_id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',sale_authorization_id:authorization,slug:'test-console',method:'auction',title:'Test Console',description:'Public description',price:'100000',increment:'10000',duration_hours:'2',collection_point:'Blantyre',terms_version:'test-v1',image:'https://example.invalid/test.webp',defects:'Used',reason:'Publish approved asset'})}') as d`)).rows[0].d;
await as('anon');assert.equal((await db.query('select * from public.public_catalog')).rows.length,0);console.log('PASS: pending listings hidden');
await db.exec('reset role');const req=(await db.query(`select id from public.approval_requests where action_type='publish_listing'`)).rows[0].id;
await as('authenticated',approver);await db.query(`select public.approve_action('${req}','approved','Publication review complete')`);
await as('anon');const cat=(await db.query('select * from public.public_catalog')).rows[0];assert.equal(cat.title,'Test Console');assert.equal(cat.external_loan_id,undefined);assert.equal(cat.borrower_reference,undefined);console.log('PASS: public catalogue safe projection');
await as('authenticated',buyer);await rejects(`insert into public.bids(auction_listing_id,bidder_id,amount) values('${listing.id}','${buyer}',100000)`,/permission denied/);
await db.query(`select public.place_bid('${listing.id}',100000)`);await rejects(`select public.place_bid('${listing.id}',110000)`,/highest bidder/);await as('authenticated',other);await rejects(`select public.place_bid('${listing.id}',105000)`,/below/);await db.query(`select public.place_bid('${listing.id}',110000)`);console.log('PASS: bids use authoritative minimum and reject direct writes');
await db.exec('reset role');await db.exec(`update public.auctions set ends_at=clock_timestamp()+interval '30 seconds' where listing_id='${listing.id}'`);await as('authenticated',buyer);await db.query(`select public.place_bid('${listing.id}',120000)`);await db.exec('reset role');assert.equal((await db.query(`select extension_count from public.auctions where listing_id='${listing.id}'`)).rows[0].extension_count,1);console.log('PASS: late qualifying bid extends auction');
await db.exec(`update public.auctions set starts_at=clock_timestamp()-interval '1 hour',ends_at=clock_timestamp()-interval '1 second' where listing_id='${listing.id}'`);await as('authenticated',other);await rejects(`select public.place_bid('${listing.id}',130000)`,/not open/);await as('service_role');await db.query('select public.close_auctions()');await db.query('select public.close_auctions()');await db.exec('reset role');const orders=(await db.query('select * from public.orders')).rows;assert.equal(orders.length,1);const order=orders[0];assert.equal(order.buyer_id,buyer);console.log('PASS: server closure rejects late bid and creates only one winner order');
await as('authenticated',other);assert.equal((await db.query('select * from public.orders')).rows.length,0);await rejects(`update public.orders set status='paid' where id='${order.id}'`,/permission denied/);console.log('PASS: buyer cannot read another buyer order or mark paid');
await as('authenticated',buyer);const payment=(await db.query(`select public.begin_payment('${order.id}') as d`)).rows[0].d;await rejects(`select public.confirm_verified_payment('${payment.tx_ref}',120000,'MWK','provider-1','{}')`,/permission denied/);
await as('service_role');await rejects(`select public.confirm_verified_payment('${payment.tx_ref}',120001,'MWK','provider-1','{}')`,/mismatch/);await db.query(`select public.confirm_verified_payment('${payment.tx_ref}',120000,'MWK','provider-1','{}')`);await db.query(`select public.confirm_verified_payment('${payment.tx_ref}',120000,'MWK','provider-1','{}')`);await db.exec('reset role');assert.equal((await db.query('select * from public.settlements')).rows.length,1);assert.equal((await db.query("select sum(direction*amount) as total from public.settlement_lines where line_type<>'SHORTFALL'")).rows[0].total,'0.00');console.log('PASS: exact payment match, idempotency and balanced settlement');
await rejects('delete from public.audit_events',/Append-only/);await rejects('delete from public.bids',/Append-only/);console.log('PASS: immutable bids and audit');
await as('authenticated',maker);await rejects(`select public.release_asset('${order.id}','invalid','Buyer','ID-1','Handover')`,/must match/);console.log('PASS: release blocked without approval and valid token');

await db.exec('reset role');
const settlementId=(await db.query('select id from public.settlements')).rows[0].id;
await as('authenticated',maker);
const settleRequest=(await db.query(`select public.request_change('settlement','${settlementId}','{"reason":"Finance review"}') as d`)).rows[0].d;
await as('authenticated',approver);await db.query(`select public.approve_action('${settleRequest.id}','approved','Finance allocations checked')`);
await db.exec('reset role');assert.equal((await db.query('select * from public.integration_outbox')).rows.length,1);console.log('PASS: settlement approval creates durable loan outbox');
await as('authenticated',maker);
const releaseRequest=(await db.query(`select public.request_change('release','${order.id}','{"collector_name":"Buyer","collector_ref":"ID-***-1","reason":"Identity checked"}') as d`)).rows[0].d;
await as('authenticated',approver);await db.query(`select public.approve_action('${releaseRequest.id}','approved','Collector authorized')`);
await as('authenticated',buyer);const note=(await db.query("select message from public.notifications where kind='collection_ready'")).rows[0].message;const releaseCode=note.split(': ')[1];
await as('authenticated',maker);await db.query(`select public.release_asset('${order.id}','${releaseCode}','Buyer','ID-***-1','Handover signed')`);await rejects(`select public.release_asset('${order.id}','${releaseCode}','Buyer','ID-***-1','Duplicate handover')`,/must match/);console.log('PASS: approved identity-matched release is single use');
await as('authenticated',approver);const metrics=(await db.query('select public.dashboard_metrics() as d')).rows[0].d;assert.equal(metrics.chart.length,6);assert.equal(metrics.kpis.recovered,120000);console.log('PASS: dashboard totals use approved financial ledger');
await db.close();console.log('All database security and workflow tests passed.');
