const tasks=[];function test(name,fn){tasks.push([name,fn]);}
import assert from 'node:assert/strict';import fs from 'node:fs/promises';import ts from 'typescript';
const source=await fs.readFile(new URL('../lib/domain.ts',import.meta.url),'utf8');const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;const {minorUnits,decimalAmount,settlement,paymentMatches,canApprove,validSignature}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
test('money uses exact minor units',()=>{assert.equal(minorUnits('123456789.99'),12345678999n);assert.equal(decimalAmount(12345678999n),'123456789.99');for(const v of ['1.001','-1','NaN','1e6'])assert.throws(()=>minorUnits(v));});
test('settlement balances with surplus and shortfall',()=>{const s=settlement(2000000000n,40000000n,1850000000n);assert.equal(s.recovery+s.surplus+s.fees,s.gross);assert.equal(s.surplus,110000000n);assert.equal(settlement(100n,10n,200n).shortfall,110n);assert.throws(()=>settlement(100n,101n,0n));});
test('payment must match provider status, reference, currency and exact amount',()=>{const p={tx_ref:'PC-1',amount:'420000.00',currency:'MWK'};const v={...p,status:'success'};assert.equal(paymentMatches(p,v),true);for(const patch of [{tx_ref:'PC-2'},{amount:'420001'},{currency:'USD'},{status:'pending'}])assert.equal(paymentMatches(p,{...v,...patch}),false);});
test('maker checker is separate from role',()=>{assert.equal(canApprove(4,'same','same',3),false);assert.equal(canApprove(2,'maker','checker',3),false);assert.equal(canApprove(3,'maker','checker',3),true)});
test('webhook HMAC rejects modified payloads and malformed signatures',async()=>{const key=await crypto.subtle.importKey('raw',new TextEncoder().encode('test-secret'),{name:'HMAC',hash:'SHA-256'},false,['sign']);const bytes=new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode('{"tx_ref":"1"}')));const sig=Array.from(bytes,x=>x.toString(16).padStart(2,'0')).join('');assert.equal(await validSignature('{"tx_ref":"1"}',sig,'test-secret'),true);assert.equal(await validSignature('{"tx_ref":"2"}',sig,'test-secret'),false);assert.equal(await validSignature('{}','invalid','test-secret'),false)});

for(const [name,fn] of tasks){await fn();console.log("PASS:",name);}
